### PR TITLE
WIP adding hackday news

### PR DESCRIPTION
**Pull request by dbu**
@dantleech moved your news here - please update with some more details once you have them, then lets publish this.

### CODE REVIEW

**Comment by dantleech** [comment]
Thanks David. What else do you think we need to add?

- How to get there (from airport, by Car, by Train, etc.)
- Some method to register (as you suggested)
- Accomodation possiblities

**Comment by dbu** [comment]
in the past, we had a wiki page with the detailed information (accomodation, travel). i think the news should have
* some general text that motivates people to come
* a link to the wiki page with organisational details
* a link to somehow register for the event

**Comment by lsmith77** [comment]
this can be closed now?

**Comment by dantleech** [comment]
Yep

**Pull request closed without merging**
