### PR TITLE
add the talk information to the blocks

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
...

### CODE REVIEW

**Comment by dbu** [comment]
cool!

afaik the english spelling is munich, not munic.
and there is a syntax error in the yml file https://travis-ci.org/symfony-cmf/symfony-cmf-website/builds/86706851 . can you please update

**Comment by ElectricMaxxx** [comment]
@dbu done

**Comment by lsmith77** [comment]
fixed displaying of the talks in https://github.com/symfony-cmf/symfony-cmf-website/commit/b40b29302ae77c7ab505815beacc7a80f6c25cd1

**Comment by dbu** [comment]
thanks!

**Pull request merged**
