### PR TITLE
add talk block for symfony usergroup talk in june 2016

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
just a talk block to notice my talk tomorrow.

### CODE REVIEW

**Comment by dbu** [comment]
also cited the tweet by the user group with the symfony cmf twitter account...

**Comment by ElectricMaxxx** [comment]
Thx. recognized and retweeted. :-)

**Comment by ElectricMaxxx** [comment]
@dbu btw is it difficult to hook our twitter-account on such changes?
means: Talk/Eventblock added -> Twitter-API -> tweet. All marketing guys
would kill for such a feature.

**Comment by dbu** [comment]
the adding in this system is a re-deployment and rebuilding static
content. i don't see how to detect that and trigger a tweet. during the
deployment, the application does not know what is new and what already
existed...

on the other hand, a manual tweet can be optimized to fit into a tweet,
instead of shortening to the character limit and have a meaningless tweet.

within a cmf admin interface, it would be possible to do something like
this i guess. e.g. when a page is published, tweet the title and the
link to the page.

**Pull request merged**
