### PR TITLE
announce 2.0 RC1

### PR DESCRIPTION
**Pull request by dbu**

### CODE REVIEW

**Comment by dbu** [comment]
@lsmith77 suggests "maybe highlight some of the key improvements beyond supporting symfony 3.* ?"

**Comment by dbu** [comment]
wouter: 
* make the message sound more positive
* Mention that MenuBundle released 2.1 and not 2.0, but it still includes BC breaks
* (and maybe a small note to say "Hey, you can also reach us in the `#symfony_cmf` channel of [Symfony slack](https://slackinvite.me/to/symfony-devs)!"

main features are symfony 3 support and moving the admins out. and getting rid of deprecated code. no big new stuff is added.

**Comment by wouterj** [comment]
There are more new features in 2.0 RC1: RoutingAuto has lots of nice changes (biggest one is allowing multiple routes for one document, e.g. to create REST APIs). And TreeBrowserBundle 2.0 RC1 is very close to be released, which is completely revisited and now features a nice GUI and UI, better javascript libraries and a tree browser form type.

**Comment by wouterj** [comment]
And SeoBundle has a new depth guesser and last modified date guesser for the sitemap.

**Comment by dbu** [comment]
thanks for the inputs, added all of that to the post

**Comment by dbu** [comment]
should we mention that some bundles are currently unmaintained because we focus our energies on the core parts?

**Comment by dbu** [comment]
added a note for the unmaintained bundles. can we release this announcement now?

**Comment by wouterj** [comment]
Pushed a commit updating the article a bit. Not much big changes (except from adding Resource as a feature).

Imo, this is ready to be published.

**Pull request merged**
